sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  redis:
    # 无密码
    host: localhost
    port: 6379
    database: 1 # 使用1号数据库（Redis默认为我们创建了16个数据库）

  aliyun.oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    #Caution: 调用Windows系统环境变量
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
    bucket-name: sky-zsh-cs
